answers = [
        {"question": "Is the sky blue?", "answer": True},
        {"question": "Does the sun rise in the east?", "answer": True},
        {"question": "Is water wet?", "answer": False},
        {"question": "Are dogs mammals?", "answer": True},
        {"question": "Is the Earth flat?", "answer": False},
        {"question": "Is 1 + 1 equal to 3?", "answer": False},
        {"question": "Do all birds fly?", "answer": False},
        {"question": "Is Python a programming language?", "answer": True},
        {"question": "Is the moon a planet?", "answer": False},
        {"question": "Are all bananas yellow?", "answer": False},
        {"question": "Is the Statue of Liberty in New York?", "answer": True},
        {"question": "Are sharks considered fishes?", "answer": True},
        {"question": "Is the capital of Iraq Baghdad?", "answer": True},
        {"question": "Are elephants bigger than ants?", "answer": True},
        {"question": "Do plants need sunlight to grow?", "answer": True},
        {"question": "Is the Pacific Ocean the largest ocean on Earth?", "answer": True},
        {"question": "Is the Mona Lisa a famous painting?", "answer": True},
        {"question": "Is the Earth the third planet from the sun?", "answer": True},
        {"question": "Is chocolate a vegetable?", "answer": False},
        {"question": "Is the Eiffel Tower in Germany?", "answer": False},
    ]